version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: post-app
    volumes: 
      - ".:/app"
    env_file:
      - .env
    ports:
      - "80:80"
    tty: true